server:
  port: 8080

kafka:
  reactive:
    consumer:
      bootstrap-servers: localhost:29092,localhost:39092
      client-id: pigeon-processor-consumer-id-${random.uuid}
      group-id: pigeon-processor-consumer-group-${random.uuid}
      topic: pigeon-processor-consumer
      partitions: 1
      replications: 1
    publisher:
      bootstrap-servers: localhost:8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/pigeon
